import { AbpHttpInterceptor, RefreshTokenService } from '@abp/abpHttpInterceptor';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';

@NgModule({
    providers: [ApiServiceProxies.LossEventsServiceProxy,
        ApiServiceProxies.LossEventTasksServiceProxy,
        ApiServiceProxies.LossTypesServiceProxy,
        ApiServiceProxies.KeyRiskIndicatorsServiceProxy,
        ApiServiceProxies.BusinessObjectivesServiceProxy, 
        ApiServiceProxies.WorkingPaperReviewCommentsServiceProxy,        
        ApiServiceProxies.LibraryControlsServiceProxy,
        ApiServiceProxies.LibraryRisksServiceProxy,
        ApiServiceProxies.DepartmentRatingHistoryServiceProxy,
        ApiServiceProxies.RatingsServiceProxy,
        ApiServiceProxies.WorkspaceServiceProxy,
        ApiServiceProxies.ProjectsServiceProxy,
        ApiServiceProxies.ProcessRiskControlsServiceProxy,
        ApiServiceProxies.ProcessRisksServiceProxy,
        ApiServiceProxies.ProcessesServiceProxy,
        ApiServiceProxies.WorkingPaperNewsServiceProxy,
        ApiServiceProxies.ExceptionIncidentsServiceProxy,
        ApiServiceProxies.TestingTemplatesServiceProxy,
        ApiServiceProxies.DepartmentRiskControlsServiceProxy,
        ApiServiceProxies.DepartmentRisksServiceProxy,
        ApiServiceProxies.DepartmentsServiceProxy,
        ApiServiceProxies.DataListsServiceProxy,
        ApiServiceProxies.ExceptionTypesServiceProxy,
        ApiServiceProxies.ControlsServiceProxy,
        ApiServiceProxies.RisksServiceProxy,
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
